### ISSUE TITLE
Allow refunds at the tail end.

### ISSUE THREAD

**Issue by MicahZoltu** [paritytech/second-price-auction#17]
https://github.com/paritytech/second-price-auction/blob/master/src/contracts/SecondPriceAuction.sol#L96

This line will result in a ton of transaction spam at the end of the auction that will clog up the network and burn a lot of gas needlessly.  When the auction is coming to a close, the FOMO will kick in and people will scramble to buy the last bits.  This will result in people sending transactions to max out the remaining amount but other users will get in first (especially because transaction ordering by miners is non-deterministic with a gas cap).  These people will then have their transactions fail, burning all of the gas in the transaction, and then they will try again with the new max value, which will once again be wrong by the time they get in.

Recommendation: Refund any amount in excess of the cap to the caller.

**Comment by keorn** [comment]
User interface should prevent one from making this mistake.

**Comment by MicahZoltu** [comment]
A UI can't resolve this issue as its a race issue with transaction submission vs transaction mining.  If the auction has 10 ETH remaining and 1 person submits a transaction for 1 ETH and 9 people submit a transaction for 10 ETH at the same time then if the 1 ETH transaction is mined first the other 9 transactions will fail.  The UI will show the user there is 10 ETH remaining and let them submit a transaction for 10 ETH, but since there is no guarantee of ordering you may be creating a transaction that is executed against a different set of data.

**Comment by gavofyork** [comment]
there will always be a race condition in that situation. the only thing a final refund will do is ensure that *one* transaction succeeds rather than none. given the price is dropping anyway which closes the sale in and of itself, i can't see that there would not be many more wasted tx fees in reality.

an earlier version of this contract actually did refund, but the code was non-trivial and on balance i'd prefer to KISS rather than squeeze out the last few drops of ether.
